# database
db.url = "jdbc:mysql://localhost/library?characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&enabledTLSProtocols=TLSv1.2&serverTimezone=UTC"
db.user = "library_admin"
db.password = "secure_library_pass"

flyway.run = [migrate]
